### ISSUE TITLE
LLVM-Clang on Windows: Cannot specify include directories for target "dMath"

### ISSUE THREAD

**Issue by jonesmz** [MADEAPPS/newton-dynamics#253]
> CMake Error at 3rdparty/newton-dynamics/sdk/dMath/CMakeLists.txt:37 (target_include_directories):
>   Cannot specify include directories for target "dMath" which is not built by
>   this project.

This is caused by this github action configuration
```
name: Windows

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
	fetch-depth: 1
        submodules: recursive

    - uses: egor-tensin/setup-clang@v1
      if: ${{ matrix.compiler == 'clang' }}

    - uses: ashutoshvarma/setup-ninja@v1.1
      if: ${{ matrix.compiler == 'clang' }}

    - name: Configure (Clang)
      env:
	CC:  C:\Program Files\LLVM\bin\cc.exe
        CXX: C:\Program Files\LLVM\bin\c++.exe
      run: |
	cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -GNinja
```

Which is because of this cmake configuration code in sdk/dMath/CMakeLists.txt
```
if (UNIX OR MINGW)
        if(NEWTON_BUILD_SHARED_LIBS)
           add_library(${projectName} SHARED ${CPP_SOURCE})
        else(NEWTON_BUILD_SHARED_LIBS)
           add_library(${projectName} STATIC ${CPP_SOURCE})
        endif(NEWTON_BUILD_SHARED_LIBS)
endif (UNIX OR MINGW)
```

I can't think of any reason why if(UNIX OR MINGW) should be here. MSVC supports static and dynamic libraries the same as Unix-like environments.
